cephfsCtrlpluginSa:
  serviceAccount:
    annotations: {}
cephfsNodepluginSa:
  serviceAccount:
    annotations: {}
controllerManager:
  manager:
    args:
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    env:
      csiServiceAccountPrefix: ceph-csi-operator-
      watchNamespace: ""
    image:
      repository: quay.io/cephcsi/ceph-csi-operator
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
nfsCtrlpluginSa:
  serviceAccount:
    annotations: {}
nfsNodepluginSa:
  serviceAccount:
    annotations: {}
rbdCtrlpluginSa:
  serviceAccount:
    annotations: {}
rbdNodepluginSa:
  serviceAccount:
    annotations: {}
snapshotController:
  replicas: 2
  serviceAccount:
    annotations: {}
  snapshotController:
    args:
    - --v=5
    - --leader-election=true
    image:
      repository: registry.k8s.io/sig-storage/snapshot-controller
      tag: v8.2.0
    imagePullPolicy: IfNotPresent
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
